blog/urls.py
from django.urls import path
import mainApp.views
from .views import BlogView, BlogPostView, AddBlogPostView, EditPostView, DeletePostView, CategoryView

app_name = "blog"

urlpatterns = [
    path('', BlogView.as_view(), name="blog"),
    path('blog/', BlogView.as_view(ordering='date'), name="blog"),
    path('blog-sort-by-title/', BlogView.as_view(ordering='title'), name="blog_title"),
    path('article/<int:pk>', BlogPostView.as_view(), name="article-detail"),
    path('addPost/', AddBlogPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', EditPostView.as_view(), name="edit_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),
    path('category/<str:cat>/<str:sort>', CategoryView, name='category'),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = "notifications"

urlpatterns = [
    path('add_subscription/<int:pageId>/', views.add_subscription, name="add_subscription"),
    path('delete_subscription/<int:subId>/', views.delete_subscription, name="delete_subscription"),
    path('notify_subscribers/<int:pageId>/', views.notify_subscribers, name="notify_subscribers"),
    path('notify_result/', views.notify_result, name="notify_result"),
    path('view_subscriptions/', views.view_subscriptions, name="view_subscriptions"),
    
]

team1site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('courses/',include('courses.urls')),
    path('notifications/', include('notifications.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from mainApp.models import Page

# Create your models here.

class BlogArticle(Page) :
    categories = (
        ('Django tutorial', 'Django tutorial'),
        ('News', 'News'),
        ('Miscellaneous', 'Miscellaneous'),
    )
    
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    image = models.URLField(default=None, null=True)
    category = models.CharField(max_length=200, default='Miscellaneous', choices=categories)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('blog:blog')

blog/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import BlogArticle
from django.urls import reverse_lazy

# Create your views here.
# def blogIndex(request):
#     return render(request, 'blogIndex.html')


class BlogView(ListView):
    model = BlogArticle
    template_name = "blog/blogIndex.html"
    ordering = ["-date"]

class BlogPostView(DetailView):
    model = BlogArticle
    template_name = "blog/blogPost.html"


class AddBlogPostView(CreateView):
    model = BlogArticle
    template_name = "blog/addBlogPost.html"
    fields = "__all__"


class EditPostView(UpdateView):
    model = BlogArticle
    template_name = "blog/editBlogPost.html"
    fields = "__all__"


class DeletePostView(DeleteView):
    model = BlogArticle
    template_name = "blog/deleteBlogPost.html"
    success_url = reverse_lazy("blog:blog")


def CategoryView(request, cat, sort):
    category_post = BlogArticle.objects.filter(category=cat).order_by(sort)
    return render(
        request, "blog/categories.html", {"cat": cat, "category_post": category_post, "sort": sort}
    )

blog/templates/blog/addBlogPost.html
{% extends 'mainApp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<h1>Add New Blog Post</h1>
<br/>

<form method="POST">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <button class="btn btn-success">Post</button>
</form>
</div>
{% endblock %}

blog/templates/blog/blogIndex.html
{% extends 'mainApp/base.html' %}


{% block content %}


<div class="container">
	<h1> The Blog </h1>
	<table style="width:20%">
	<tr>
		<td>
			<div class="dropdown">
				<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
				aria-haspopup="true" aria-expanded="false" data-intro="You can select a category of topics to filter on">
					Categories
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<a class="dropdown-item" href="{% url 'blog:category' 'Django tutorial' '-date' %}">Django tutorial</a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item" href="{% url 'blog:category' 'News' '-date' %}">News</a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item" href="{% url 'blog:category' 'Miscellaneous' '-date' %}">Miscellaneous</a>
				</div>
			</div>

			<br/>
		</td>

		<td>
			<div class="dropdown">
				<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" 
				aria-haspopup="true" aria-expanded="false" data-intro="You change the sort order here.">
					Sort By
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<a class="dropdown-item" href="{% url 'blog:blog' %}">Date</a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item" href="{% url 'blog:blog_title' %}">Title</a>
				</div>
			</div>
			<br/>
		</td>
	</tr>
	</table>


	<div class="grid">
		{% for x in object_list %}

		<article class="blog-card">
			<a href="{% url 'blog:article-detail' x.pk %}" class="text"><h3>{{ x.title }}</h3></a><br/>
			<a href="{% url 'blog:article-detail' x.pk %}"><img src="{{ x.image }}"> </a>

			<div class="text">
				

				Posted by {{ x.author }}
				{% if user.is_staff %}
				<small> - 
					<a href="{% url 'blog:edit_post' x.pk %}">(Edit)</a>
					<a href="{% url 'blog:delete_post' x.pk %}">(Delete)</a>
				</small>
				{% endif %}	
				<br/>
				
				Category - <a href="{% url 'blog:category' x.category '-date' %}">{{ x.category }}</a><br />
				{{ x.date }}<br/>
				
				
			</div>

		  </article>


		{% endfor %}


	</div>






</div>


{% endblock %}

blog/templates/blog/blogPost.html
{% extends 'mainApp/base.html' %}


{% block content %}
<div class="container">
	<h1>{{ object.title }}</h1>
	Posted by {{ object.author }}
	{% if user.is_authenticated %}
		{% if user.id == object.author.id %}
		<small> - 
			<a href="{% url 'blog:edit_post' object.pk %}">(Edit)</a>
			<a href="{% url 'blog:delete_post' object.pk %}">(Delete)</a>
		</small><br/>
		{% endif %}
	{% endif %}
	Category - <a href="{% url 'blog:category' object.category '-date' %}">{{ object.category }}</a><br />
	{{ object.date }}


    {% if user.is_authenticated %}
		<br>
		<a href="{% url 'notifications:add_subscription' object.id %}" 
		data-intro="Click on this link if you want to receive an email when this article is updated.">
			Subscribe to this article</a>
	{% endif %}

	{% if user.is_staff %}
		<br>
		<a href="{% url 'notifications:notify_subscribers' object.id %}">
			<button class="btn-danger btn-notify-subscribers" type="submit">Notify Subscribers</button>
		</a>
	{% endif %}	
	
	<hr>
	<br />
	<img src="{{ object.image }}"><br />
	{{ object.body|safe }}
	<br />
	<br />
	<a href="{% url 'blog:blog' %}">Back</a>
</div>
{% endblock %}

blog/templates/blog/categories.html
{% extends 'mainApp/base.html' %}


{% block content %}


<div class="container">
	<h1> The Blog  - {{ cat }}</h1>
	<table style="width:20%">
		<tr>
		<td>
		<div class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Categories
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			  <a class="dropdown-item" href="{% url 'blog:category' 'Django tutorial' '-date' %}">Django tutorial</a>
			  <div class="dropdown-divider"></div>
			  <a class="dropdown-item" href="{% url 'blog:category' 'News' '-date' %}">News</a>
			  <div class="dropdown-divider"></div>
			  <a class="dropdown-item" href="{% url 'blog:category' 'Miscellaneous' '-date' %}">Miscellaneous</a>
			</div>
		  </div>
		  <br/>
		</td>
		<td>
		  <div class="dropdown">
			<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Sort By
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			  <a class="dropdown-item" href="{% url 'blog:category' cat '-date' %}">Date</a>
			  <div class="dropdown-divider"></div>
			  <a class="dropdown-item" href="{% url 'blog:category' cat 'title' %}">Title</a>
			</div>
		  </div>
		  <br/>
		</td>
		</tr>
		</table>
	<ul class="list-group">
	{% for x in category_post %}
		<li class="list-group-item"><a href="{% url 'blog:article-detail' x.pk %}"><h3>{{ x.title }}</h3></a><br/>
			Posted by {{ x.author }}
			{% if user.is_authenticated %}
				{% if user.id == x.author.id %}
				<small> - 
					<a href="{% url 'blog:edit_post' x.pk %}">(Edit)</a>
					<a href="{% url 'blog:delete_post' x.pk %}">(Delete)</a>
				</small><br/>
				{% endif %}
			{% endif %}
		Category - <a href="{% url 'blog:category' x.category '-date' %}">{{ x.category }}</a><br />
		{{ x.date }}<br/>
		<a href="{% url 'blog:article-detail' x.pk %}">
			<img src="{{ x.image }}" class="img-fluid">
		</a><br/>
		{{ x.body|safe }}</li>
	{% endfor %}
	</ul>
</div>


{% endblock %}

blog/templates/blog/deleteBlogPost.html
{% extends 'mainApp/base.html' %}


{% block content %}
<div class="container">
    <h1>Delete {{ object.title }}</h1>
    <br/>
    <form method="POST">
        {% csrf_token %}
        <strong>Are you sure?</strong><br/><br/>
        <button class="btn btn-success">Delete Post</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/editBlogPost.html
{% extends 'mainApp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Edit Blog Post</h1>
    <br/>
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button class="btn btn-success">Save Changes</button>
    </form>
</div>
{% endblock %}