accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

blog/urls.py
from django.urls import path
import mainApp.views
from .views import BlogView, BlogPostView, AddBlogPostView, EditPostView, DeletePostView, CategoryView

app_name = "blog"

urlpatterns = [
    path('', BlogView.as_view(), name="blog"),
    path('blog/', BlogView.as_view(ordering='date'), name="blog"),
    path('blog-sort-by-title/', BlogView.as_view(ordering='title'), name="blog_title"),
    path('article/<int:pk>', BlogPostView.as_view(), name="article-detail"),
    path('addPost/', AddBlogPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', EditPostView.as_view(), name="edit_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),
    path('category/<str:cat>/<str:sort>', CategoryView, name='category'),
]

courses/urls.py
from django.urls import path, include
from . import views

app_name = "courses"

urlpatterns = [
    path('',views.courseHome,name="courses_home"), 
    path('details/<int:id>/',views.details,name="detail"),
    path('addreview/<int:id>/',views.add_review,name="add_review"),
    path('editreview/<int:course_id>/<int:review_id>/',views.edit_review,name="edit_review"),
    path('deletereview/<int:course_id>/<int:review_id>/',views.delete_review,name="delete_review")
]

mainApp/urls.py
from django.urls import path
from . import views

app_name = "mainApp"

urlpatterns = [
    path('', views.home, name="home"),   
    path('home/', views.home, name="home"), 
    path('not_authorized/', views.not_authorized, name="not_authorized"), 
]

notifications/urls.py
from django.urls import path
from . import views

app_name = "notifications"

urlpatterns = [
    path('add_subscription/<int:pageId>/', views.add_subscription, name="add_subscription"),
    path('delete_subscription/<int:subId>/', views.delete_subscription, name="delete_subscription"),
    path('notify_subscribers/<int:pageId>/', views.notify_subscribers, name="notify_subscribers"),
    path('notify_result/', views.notify_result, name="notify_result"),
    path('view_subscriptions/', views.view_subscriptions, name="view_subscriptions"),
    
]

team1site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('courses/',include('courses.urls')),
    path('notifications/', include('notifications.urls')),
]

mainApp/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Page(models.Model) :
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    #body = models.TextField()
    body = RichTextField(blank=True, null=True)
    

    

mainApp/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'mainApp/index.html', {})

def not_authorized(request):
    return render(request, 'mainApp/not_authorized.html', {})

mainApp/templates/mainApp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intro.js@2.9.3/minified/introjs.min.css">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    <title>Team 1 Site - Web Dev with Django</title>
  </head>


  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
      <a class="navbar-brand" href="{% url 'mainApp:home' %}" data-intro="Click here to return to the homepage. This navbar should be available anywhere on the site"
        >Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          {% if user.is_authenticated %}
            <li class="nav-item">
            <a  
              class="nav-link"
              href="javascript:introJs().setOption('showProgress', true).start();">
              Demo Tour</a>
          </li>
        {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blog' %}" data-intro="Click here to access the blog section of our site. You'll find various guides on Django and news in here.">
              Blog <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:courses_home' %}" data-intro="Click here to access the courses section of our site. Here you can find some off-site guides on Django topics along with user ratings of each!">
              Courses</a>
          </li>
          
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
            data-intro="Click here to see a drop down list of other pages related to your account, such as managing any articles that you're subscribed to.">
              {{ user.username }}
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    
              {% if user.is_staff %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'blog:add_post' %}">Add Blog Post</a>
              {% endif %}

              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'notifications:view_subscriptions' %} ">Subscribed Items</a>
              
                <div class="dropdown-divider"></div>
              
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}" data-intro="This is where you register">Register</a>
          </li>
          {% endif %}

        

        </ul>
      </div>
    </nav>

    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/intro.js@2.9.3/minified/intro.min.js"></script>

  </body>

</html>

mainApp/templates/mainApp/index.html
{% extends 'mainApp/base.html' %}


{% block content %}


<div class="container">
    </br>
    <h1>Welcome to Website Development with Django!</h1>

    <p>
        On our site you'll find information to help get you started on developing your very own website using the Django framework. Register an account with us and you can activate a demo to highlight features on this site.
    </p>

    <h4>What is Django?</h4>
    <p>
        Django is a high-level Python web framework that enables rapid development of secure and maintainable websites. Built by experienced developers, Django takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel. It is free and open source, has a thriving and active community, great documentation, and many options for free and paid-for support.
    </p>

    <h4>Why Learn Django?</h4>
    <ol>
        <li><b>Fast</li></b> <p>Many of the tedious server-client interactions are handled automatically by Django. Django also has many ready-to-go libraries to extend functionality of your site.</p>
        <li><b>Security</li></b> <p>User accounts and security are already provided with Django. Django can help prevent attacks like SQL Injection, XSS, CRSF, Clickjacking, and more.</p>
        <li><b>Admin Panel</li></b> <p>Django includes an administrative section to control your users and content. You can just add new articles this way--no need to manually create HTML pages for everything!</p>
        <li><b>Scalable​</li></b> <p>It doesn’t matter whether you are a single person or running a company. You can use Django on any type of project, and easily scale it in the future.</p>
        <li><b>Good for Data Science and Analytics​​</li></b> <p>As Django is built on Python, you can integrate existing Artificial Intelligence and Machine Learning technologies.</p>
        <li><b>Community Support</li></b> <p>Django is well-managed and documented by a fantastic community. You'll have plenty of availabe resources if you run into issues.</p>
        <li><b>Career Growth</li></b> <p>Django is highly desired in software industries.</p>
        <img src="https://cvcompiler.com/blog/wp-content/uploads/2019/04/Python-2-887x1024.png">
    </ol>


    <i>Homepage content sources: <br>
         <a href="https://dev.to/codesnail/why-you-should-learn-django-in-2020-2jhm" target="_blank">dev.to: Why you should learn django in 2020</a> <br>
         <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Introduction" target="_blank">mozilla.org: Django introduction</a> <br>
    </i>

</div>


{% endblock %}

mainApp/templates/mainApp/not_authorized.html
{% extends 'mainApp/base.html' %}


{% block content %}
    <h2>You are not authorized to perform that operation.</h2>

{% endblock %}