blog/urls.py
from django.urls import path
import mainApp.views
from .views import BlogView, BlogPostView, AddBlogPostView, EditPostView, DeletePostView, CategoryView

app_name = "blog"

urlpatterns = [
    path('', BlogView.as_view(), name="blog"),
    path('blog/', BlogView.as_view(ordering='date'), name="blog"),
    path('blog-sort-by-title/', BlogView.as_view(ordering='title'), name="blog_title"),
    path('article/<int:pk>', BlogPostView.as_view(), name="article-detail"),
    path('addPost/', AddBlogPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', EditPostView.as_view(), name="edit_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),
    path('category/<str:cat>/<str:sort>', CategoryView, name='category'),
]

courses/urls.py
from django.urls import path, include
from . import views

app_name = "courses"

urlpatterns = [
    path('',views.courseHome,name="courses_home"), 
    path('details/<int:id>/',views.details,name="detail"),
    path('addreview/<int:id>/',views.add_review,name="add_review"),
    path('editreview/<int:course_id>/<int:review_id>/',views.edit_review,name="edit_review"),
    path('deletereview/<int:course_id>/<int:review_id>/',views.delete_review,name="delete_review")
]

team1site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('courses/',include('courses.urls')),
    path('notifications/', include('notifications.urls')),
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Course(models.Model):
    # fields for the course table.
    name = models.CharField(max_length=800)
    creator = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    last_updated_date = models.DateField() 
    average_rating = models.FloatField()
    image = models.URLField(default=None,null=True)

    def __str__(self):
        return self.name 
    
    def __unicode(self):
        return self.name

class Review(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

courses/forms.py
from django import forms
from .models import *

#course add form
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('name','creator','description','last_updated_date','average_rating','image')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment","rating")

courses/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.db.models import Avg
from django.shortcuts import redirect
from .forms import *

# Create your views here.
def courseHome(request):
    allCourses = Course.objects.all()
    
    context = {
        "courses": allCourses
    }

    return render(request,'courses/courseshome.html', context)

def details(request,id):
    course = Course.objects.get(id=id)
    reviews = Review.objects.filter(course=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0.0
    average = round(average,2)
    context= {
        "course":course,
        "reviews": reviews,
        "average":average
    }
    return render(request, 'courses/details.html',context)

def add_review(request, id):
    if request.user.is_authenticated:
        course = Course.objects.get(id=id)
        if request.method == 'POST':
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit = False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.course = course
                data.save()
                return redirect("courses:detail",id)
            else:
                form = ReviewForm()
            return redirect("courses:detail",id)
    else:
        return redirect("accounts:login")

def edit_review(request, course_id, review_id):
    if request.user.is_authenticated:
        course = Course.objects.get(id=course_id)
        review = Review.objects.get(course = course, id= review_id)

        if request.user == review.user:

            if request.method == "POST":
                form = ReviewForm(request.POST, instance= review)
                if form.is_valid():
                    data = form.save(commit = False)
                    if(data.rating > 5) or (data.rating < 0):
                         error = "Out or range. Please select rating from 0 to 5."
                         return render(request, 'courses/editreview.html', {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("courses:detail", course_id)
            else:
                form= ReviewForm(instance=review)
            return render(request,'courses/editreview.html',{"form":form})

        else:
            return redirect("courses:detail",course_id)
    else:
        return redirect("accounts:login")

def delete_review(request, course_id, review_id):
    if request.user.is_authenticated:
        course = Course.objects.get(id=course_id)
        review = Review.objects.get(course = course, id= review_id)

        if request.user == review.user:
             review.delete()
        return redirect("courses:detail",course_id)
    else:
        return redirect("accounts:login") 

courses/templates/courses/courseshome.html
{% extends 'mainApp/base.html' %}


{% block content %}


<div class="container">
    <br>
    <div class="card" id= "backdrop">
         <div class="card-body" data-intro="Thumbnails of each course are here. Click on &quotRead More to view each information on a course&quot">
             <div class="row">
                 {% for course in courses %}
                 <div class="col-md-4">
                     <div class="card" >
                         <div class="card-body">
                             <div class="text-center">
                             <img src="{{ course.image }}" alt="" class="img-fluid" width="100%">
                             <h4 class="text-center">{{course.name}}</h4>
                             <div class="text-center">
                             <i class="text-center">{{course.last_updated_date}}</i>
                             </div>
                             <a href="{% url 'courses:detail' course.id %}">Read More</a>
                             </div>
                         </div>
                     </div>
                 </div>
                 {% endfor %}
             </div>
         </div>
    </div>
</div>

{% endblock %}

courses/templates/courses/details.html
{% extends 'mainApp/base.html' %}


{% block content %}



<br>
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ course.image }}" alt="{{course.name}}" class="img-fluid">
                </div>
                <div class="col-md-8">
                    <h3 class= "text-center">
                        {{course.name}}
                    </h3>
                    <p data-intro="Here's a description summary of the course."> {{course.description}}</p>
                    <h5>Course Creator: {{ course.creator }}</h5>
                    <h5>Last Updated Date: {{ course.last_updated_date }}</h5>
                    <h5 data-intro="Here's the average user rating of this course.">Star Rating: {{ average }}/5</h5>
                </div>
            </div>
        </div>
    </div>


<br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <form action="{% url 'courses:add_review' course.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">Star Rating</label>
                <input type="range" id="rangeInput" 
                    name="rating" min="0" max="5" value="0" step="0.5"
                    oninput="amount.value=rangeInput.value">                                                       
         
         <output name="amount" id="amount" for="rangeInput">0</output>
                
                <br>
                <input type="submit" class="btn btn-danger" value="Add Review" 
                    data-intro="Add some text to your review, assign a score with the slider, and then post it here!">
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
                <div class="card" style="background-color: #f5eeee;" data-intro="Here's all the individual user reviews for this course.">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5 class="text-left">{{ review.user.username }}</h5>
                                <h5>{{ review.rating }}</h5>
                                {% if request.user == review.user %}
                                <a href="{% url 'courses:edit_review' course.id review.id %}">Edit</a>
                                <a href="{% url 'courses:delete_review' course.id review.id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                                {% endif %}
                            </div>
                            <div class="col-md-9">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

courses/templates/courses/editreview.html
{% extends 'mainApp/base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}