blog/urls.py
from django.urls import path
import mainApp.views
from .views import BlogView, BlogPostView, AddBlogPostView, EditPostView, DeletePostView, CategoryView

app_name = "blog"

urlpatterns = [
    path('', BlogView.as_view(), name="blog"),
    path('blog/', BlogView.as_view(ordering='date'), name="blog"),
    path('blog-sort-by-title/', BlogView.as_view(ordering='title'), name="blog_title"),
    path('article/<int:pk>', BlogPostView.as_view(), name="article-detail"),
    path('addPost/', AddBlogPostView.as_view(), name="add_post"),
    path('article/edit/<int:pk>', EditPostView.as_view(), name="edit_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),
    path('category/<str:cat>/<str:sort>', CategoryView, name='category'),
]

notifications/urls.py
from django.urls import path
from . import views

app_name = "notifications"

urlpatterns = [
    path('add_subscription/<int:pageId>/', views.add_subscription, name="add_subscription"),
    path('delete_subscription/<int:subId>/', views.delete_subscription, name="delete_subscription"),
    path('notify_subscribers/<int:pageId>/', views.notify_subscribers, name="notify_subscribers"),
    path('notify_result/', views.notify_result, name="notify_result"),
    path('view_subscriptions/', views.view_subscriptions, name="view_subscriptions"),
    
]

team1site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('courses/',include('courses.urls')),
    path('notifications/', include('notifications.urls')),
]

notifications/models.py
from django.db import models
from mainApp.models import Page
from django.contrib.auth.models import User

# Create your models here.

class Subscription(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    last_notified = models.DateTimeField(blank=True, null=True)

notifications/views.py
from django.shortcuts import render, redirect
from mainApp.models import Page
from django.http import HttpResponse

from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context

from django.urls import reverse

from .models import *


# Create your views here.

def view_subscriptions(request):

    if request.user.is_authenticated:
        subs = Subscription.objects.all().filter(user=request.user)

        return render(request, 'notifications/view_subscriptions.html', {'subscriptions': subs})
    else:
        return redirect("accounts:login")

def add_subscription(request, pageId) :

    if request.user.is_authenticated:
        page = Page.objects.get(id=pageId)
        
        try:
            pass
        except:
            pass

        try:
            sub = Subscription.objects.get(page=page, user=request.user)
            #user is already subscribed, nothing to do
        except Subscription.DoesNotExist:
            sub = Subscription()
            sub.user = request.user
            sub.page = page
            sub.save()
        return redirect("notifications:view_subscriptions")
    else:
        return redirect("accounts:login")

def delete_subscription(request, subId):
    
    if request.user.is_authenticated:
        
        try:
            sub = Subscription.objects.get(id=subId, user=request.user)

            if sub.user == request.user:
                sub.delete()
                return redirect("notifications:view_subscriptions")
            else:
                return redirect("mainApp:not_authorized")

        except Subscription.DoesNotExist:
            return redirect("mainApp:not_authorized")
    else:
        return redirect("accounts:login")

def notify_subscribers(request, pageId) :

    if not request.user.is_staff:
        return redirect("mainApp:not_authorized")
    
    subs = Subscription.objects.filter(id=pageId)

    for curSub in Subscription.objects.filter(page_id=pageId):
        curSubUser = User.objects.get(id=curSub.user_id)
        
        if(curSubUser.email != ''):
            print("sending email to: " + curSubUser.email)

            plainTemplate = get_template('notifications/email_notification.txt')
            htmlTemplate = get_template('notifications/email_notification.html')


            subject = 'Subscribed page has been updated'
            from_email = 'webdevwithdjango@gmail.com'
            to = [curSubUser.email]


            #I'm assuming that only blog articles are getting subscriptions with the pageURL handling.
            context = { 
                'title': curSub.page.title,
                'pageURL':  request.build_absolute_uri(reverse('blog:article-detail', args=[curSub.page.id]) )
            }
            plainContent = plainTemplate.render(context)
            htmlContent = htmlTemplate.render(context)

            #print(plainContent)

            msg = EmailMultiAlternatives(subject, plainContent, from_email, to)
            msg.attach_alternative(htmlContent, "text/html")
            msg.send()


    return redirect("notifications:notify_result")

def notify_result(request):
    return render(request, 'notifications/notifications_sent.html')

notifications/templates/notifications/add_subscription.html
{% extends 'mainApp/base.html' %}


{% block content %}


<div class="container">
	<h1>You have been subscribed.</h1>
</div>


{% endblock %}

notifications/templates/notifications/email_notification.html
One of your subscribed pages has been updated. Click the following link to visit:
<a href="{{pageURL}}"><h3>{{ title }}</h3></a>

notifications/templates/notifications/notifications_sent.html
{% extends 'mainApp/base.html' %}


{% block content %}

<h2>Notifications have been emailed to subscribed users.</h2>

{% endblock %}

notifications/templates/notifications/view_subscriptions.html
{% extends 'mainApp/base.html' %}


{% block content %}



<div class="container">

    <h1>Content subscriptions</h1>

    {% if subscriptions.count == 0 %}
        <p>You're not subscribed to anything yet, but you'll see your subscriptions here after you do so. You'll receive an email notification when there's content changes.</p>
    {% else %}
        <p>These are the pages that you are currently subscribed to. You'll receive an email notfication when there's content changes to these.</p>
    {% endif %}

    
    <ul class="list-group" data-intro="These are the pages that you're currently subscribed for email notifications. You can remove any individual subscriptions here.">
        {% for curSub in subscriptions %}
            <li class="list-group-item">
                <div>{{curSub.page.title}}</div>
                <div><a href="{% url 'notifications:delete_subscription' curSub.id %}">Remove Subscription</a></div>
            </li>            
        {% endfor %}

    </ul>
</div>


{% endblock %}